"""Add AppSetting model

Revision ID: da395b0ee495
Revises: b1020b1a8b26
Create Date: 2026-07-12 16:16:49.526433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da395b0ee495'
down_revision: Union[str, Sequence[str], None] = 'b1020b1a8b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depot_name', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('distance_unit', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_id'), 'app_settings', ['id'], unique=False)
    op.alter_column('drivers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('drivers', 'license_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('drivers', 'license_category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('drivers', 'license_expiry',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=True)
    op.alter_column('drivers', 'contact_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('drivers', 'safety_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('drivers', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('maintenance_logs', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('maintenance_logs', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('maintenance_logs', 'cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('maintenance_logs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('maintenance_logs_vehicle_id_fkey'), 'maintenance_logs', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_logs', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    op.alter_column('trips', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('trips', 'destination',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('trips', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trips', 'driver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trips', 'cargo_weight_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('trips', 'planned_distance_km',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('trips', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_trips_driver_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_vehicle_id'), table_name='trips')
    op.drop_constraint(op.f('trips_driver_id_fkey'), 'trips', type_='foreignkey')
    op.drop_constraint(op.f('trips_vehicle_id_fkey'), 'trips', type_='foreignkey')
    op.create_foreign_key(None, 'trips', 'drivers', ['driver_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'trips', 'vehicles', ['vehicle_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.create_foreign_key(op.f('trips_vehicle_id_fkey'), 'trips', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key(op.f('trips_driver_id_fkey'), 'trips', 'drivers', ['driver_id'], ['id'])
    op.create_index(op.f('ix_trips_vehicle_id'), 'trips', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    op.alter_column('trips', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('trips', 'planned_distance_km',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('trips', 'cargo_weight_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('trips', 'driver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trips', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trips', 'destination',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('trips', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'maintenance_logs', type_='foreignkey')
    op.create_foreign_key(op.f('maintenance_logs_vehicle_id_fkey'), 'maintenance_logs', 'vehicles', ['vehicle_id'], ['id'])
    op.alter_column('maintenance_logs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('maintenance_logs', 'cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('maintenance_logs', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('maintenance_logs', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('drivers', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('drivers', 'safety_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('drivers', 'contact_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('drivers', 'license_expiry',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('drivers', 'license_category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('drivers', 'license_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('drivers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_app_settings_id'), table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
